### ISSUE TITLE
There is an issue for the Test for UserProjectRepositorTest and SearchProjectInteractor

### ISSUE THREAD

**Issue by Justinfan591** [sherwinokhowat/Group-Formation-System#116]
The tests are failing.

**Comment by sherwinokhowat** [comment]
Are you sure about the UserProjectRepositoryTest? It works on my end. Can someone else let me know if it works on their end?

**Comment by cecexyzhang** [comment]
It works on my end too.

**Comment by tArthur1** [comment]
It seems to work for my side.

**Comment by cecexyzhang** [comment]
The issue in SearchProjectInteractor remains. The `testSearchProject()` has failed. Can someone resolve it?
