### ISSUE TITLE
EditProjectInteractorTest failed

### ISSUE THREAD

**Issue by cecexyzhang** [sherwinokhowat/Group-Formation-System#119]
`testEditAndSearchProject()` in `EditProjectInteractorTest` has failed. Can someone please resolve it?

**Comment by sherwinokhowat** [comment]
They don't fail on my end. Can someone else check whether they fail on their end?

**Comment by cecexyzhang** [comment]
> They don't fail on my end. Can someone else check whether they fail on their end?

I pulled the latest code in `main`, ran the full coverage test and got 
![image](https://github.com/user-attachments/assets/dc60a73c-1944-425e-8651-2249319bdda8)

And I agree that a pending merge request will close it.

**Comment by sherwinokhowat** [comment]
That error is because you do not have the API key setup in your environment variables.

**Comment by cecexyzhang** [comment]
Oh yes you're right, I never set up the API key before, but I just did and all the tests passed!
